// Bulgaars Leren — data-badges.js

var BADGES =[
{id:"l1",nm:"Eerste Letter",ic:"\u{1f524}",ds:"Je eerste letter geleerd",rq:s=>s.ll>=1},
{id:"fr",nm:"Vrienden Meester",ic:"\u{1f91d}",ds:"Alle Vrienden-letters geleerd",rq:s=>(s.gd||[]).includes("friends")},
{id:"tr",nm:"Trickster Temmer",ic:"\u{1f3ad}",ds:"Alle Tricksters doorgehad",rq:s=>(s.gd||[]).includes("tricksters")},
{id:"nf",nm:"Nieuwe Gezichten Fan",ic:"\u{1f31f}",ds:"Alle Nieuwe Gezichten geleerd",rq:s=>(s.gd||[]).includes("newfaces")},
{id:"am",nm:"Alfabet Meester",ic:"\u{1f451}",ds:"Alle 30 letters geleerd",rq:s=>s.ll>=30},
{id:"w10",nm:"Woordenvanger",ic:"\u{1f4da}",ds:"10 woorden geleerd",rq:s=>s.wl>=10},
{id:"w50",nm:"Taalheld",ic:"\u{1f31f}",ds:"50 woorden geleerd",rq:s=>s.wl>=50},
{id:"w100",nm:"Woordenmeester",ic:"\u{1f4d6}",ds:"100 woorden geleerd",rq:s=>s.wl>=100},
{id:"w150",nm:"Woordenwonder",ic:"\u{1f680}",ds:"150 woorden geleerd",rq:s=>s.wl>=150},
{id:"q5",nm:"Quiz Kampioen",ic:"\u{1f3c6}",ds:"5 quizvragen goed",rq:s=>s.qo>=5},
{id:"q20",nm:"Quiz Meester",ic:"\u{1f947}",ds:"20 quizvragen goed",rq:s=>s.qo>=20},
{id:"qp",nm:"Perfectionist",ic:"\u{1f48e}",ds:"10 op rij goed",rq:s=>s.qb>=10},
{id:"g1",nm:"Grammatica Starter",ic:"\u{1f4d0}",ds:"Eerste grammatica geleerd",rq:s=>s.gl>=1},
{id:"c1",nm:"Eerste Gesprek",ic:"\u{1f4de}",ds:"Eerste gesprek gelezen",rq:s=>s.cl>=1},
{id:"p3",nm:"Cultuur Ontdekker",ic:"\u{1f30d}",ds:"5 thema-modules gedaan",rq:s=>s.mc>=14},
{id:"w200",nm:"Woordenwizard",ic:"\u{1f9d9}",ds:"200 woorden geleerd",rq:s=>s.wl>=200},
{id:"all",nm:"Oma's Favoriet",ic:"\u{1f475}\u2764\ufe0f",ds:"Alle modules afgerond!",rq:s=>s.mc>=19},
{id:"m1",nm:"Memory Match",ic:"\u{1f0cf}",ds:"1 memory game gewonnen",rq:s=>(s.mc||0)>=1},
{id:"m5",nm:"Memory Meester",ic:"\u{1f9e0}",ds:"5 memory games gewonnen",rq:s=>(s.mc||0)>=5},
{id:"h1",nm:"Galgje Held",ic:"\u{1f620}",ds:"Eerste galgje gewonnen",rq:s=>(s.hw||0)>=1},
{id:"ws1",nm:"Woordzoeker",ic:"\u{1f50e}",ds:"Eerste woordzoeker gewonnen",rq:s=>(s.wsg||0)>=1},
{id:"ws5",nm:"Zoek Meester",ic:"\u{1f9d0}",ds:"5 woordzoekers gewonnen",rq:s=>(s.wsg||0)>=5},
{id:"sb1",nm:"Zinnen Bouwer",ic:"\u{1f3d7}\ufe0f",ds:"Eerste zin gebouwd",rq:s=>(s.sbg||0)>=1},
{id:"sb10",nm:"Zinnen Meester",ic:"\u{1f4ac}",ds:"10 zinnen gebouwd",rq:s=>(s.sbg||0)>=10},
{id:"dc7",nm:"Week Streak",ic:"\u{1f525}",ds:"7 dagen dagelijkse uitdaging",rq:s=>(s.dw||0)>=7},
{id:"dc30",nm:"Maand Streak",ic:"\u{1f4aa}",ds:"30 dagen dagelijkse uitdaging",rq:s=>(s.dw||0)>=30},
{id:"fc1",nm:"Flashcard Fan",ic:"\u{1f4c7}",ds:"Eerste flashcard sessie",rq:s=>(s.fc||0)>=1},
{id:"fc10",nm:"Flashcard Meester",ic:"\u{1f9e0}",ds:"10 flashcard sessies",rq:s=>(s.fc||0)>=10},
{id:"gf5",nm:"Grammatica Goeroe",ic:"\u{1f4dd}",ds:"5 invuloefeningen goed",rq:s=>(s.gf||0)>=5},
{id:"nm20",nm:"Telwonder",ic:"\u{1f522}",ds:"Alle getallen 1-20 geleerd",rq:s=>(s.nt||0)>=20},
{id:"cw1",nm:"Kruiswoord Kraker",ic:"\u{1f9e9}",ds:"Eerste kruiswoordpuzzel",rq:s=>(s.cw||0)>=1},
{id:"om1",nm:"Oma's Brief",ic:"\u{1f48c}",ds:"Eerste berichtje aan oma",rq:s=>(s.om||0)>=1},
{id:"lt10",nm:"Schrijver",ic:"\u270d\ufe0f",ds:"10 letters getekend",rq:s=>(s.lt||0)>=10},
{id:"ic3",nm:"Praat Koning",ic:"\u{1f451}",ds:"3 gesprekken gevoerd",rq:s=>(s.ic||0)>=3},
{id:"w300",nm:"Woordenboek",ic:"\u{1f4d5}",ds:"300 woorden geleerd",rq:s=>s.wl>=300},
{id:"srs10",nm:"Herhaal Held",ic:"🔄",ds:"10 herhaalsessies gedaan",rq:s=>{var c=0;var srs=s.srs||{};for(var k in srs){if(srs[k].cor>=2)c++;}return c>=10;}},
{id:"dm1",nm:"Nachtbraker",ic:"\u{1f319}",ds:"Donkere modus gebruikt",rq:s=>s.dm===true},
{id:"ls1",nm:"Eerste Les",ic:"\ud83c\udfaf",ds:"Eerste les afgerond",rq:s=>(s.lsn||0)>=1},
{id:"ls10",nm:"Les Meester",ic:"\ud83c\udfc5",ds:"10 lessen afgerond",rq:s=>(s.lsn||0)>=10},
{id:"cpA1",nm:"A1 Gehaald",ic:"\ud83c\udfc6",ds:"A1 checkpoint test gehaald",rq:s=>(s.cp||{}).A1===true},
{id:"cpA2",nm:"A2 Gehaald",ic:"\ud83e\udd47",ds:"A2 checkpoint test gehaald",rq:s=>(s.cp||{}).A2===true},
{id:"cpB1",nm:"B1 Gehaald",ic:"\ud83c\udf1f",ds:"B1 checkpoint test gehaald",rq:s=>(s.cp||{}).B1===true},
{id:"b1s",nm:"B1 Starter",ic:"\ud83d\ude80",ds:"50 B1-woorden geleerd",rq:s=>{var c=0;var wi=s.wi||[];for(var i=0;i<MODS.length;i++){if(MODS[i].ph===4&&MODS[i].ws){for(var j=0;j<MODS[i].ws.length;j++){if(wi.indexOf(MODS[i].ws[j].b)>=0)c++;}}}return c>=50;}},
{id:"b1m",nm:"B1 Meester",ic:"\ud83d\udc51",ds:"Alle 456 B1-woorden geleerd",rq:s=>{var c=0;var wi=s.wi||[];for(var i=0;i<MODS.length;i++){if(MODS[i].ph===4&&MODS[i].ws){for(var j=0;j<MODS[i].ws.length;j++){if(wi.indexOf(MODS[i].ws[j].b)>=0)c++;}}}return c>=456;}}];
